### ISSUE TITLE
Please fix logical error asap — trying to remove root directory

### ISSUE THREAD

**Issue by sharmaashish** [SBU-BMI/uploadHeatmaps#4]
If this fails:
https://github.com/SBU-BMI/uploadHeatmaps/blob/f0b52af02159463a6f7ea8b759fad894fe98ca6a/uploadHeatmaps.sh#L233-L234
then the exitStatus would be !0

And therefore https://github.com/SBU-BMI/uploadHeatmaps/blob/f0b52af02159463a6f7ea8b759fad894fe98ca6a/uploadHeatmaps.sh#L244
would end up trying to remove the root directory

**Comment by tkurc** [comment]
There are multiple problems/bugs with the heatmap loader. 

1. It doesn’t check for empty “result” set correctly. 

if(result == [] || !result) should be if (result==‘’ || result == [] || !result)   (Note ‘’ is double ‘ ) 

2. uploadDir is initialized to empty, and if exitStatus from “node —max_old_space …” is non-zero, uploadHeatmaps.sh will try to delete /* : 

# Check to see conversion process succeeded 
if [[ $exitStatus -eq 0 ]]
…
else
  rm -f ${uploadDir}/*
  exit $exitStatus
fi

rm -f ${uploadDir}/*  will try to remove /* because uploadDir will be empty string.
